[package]
name = "jinja-lsp-queries"
version = "0.1.6"
edition = "2021"
description = "TreeSitter queries for jinja-lsp"
license = "MIT"

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-jinja2 = "0.0.5"
tree-sitter-rust = "0.20.4"
tower-lsp = { version = "0.20.0", features = ["proposed"] }
ropey = "1.5.0"

