[package]

name = "tree_sitter_queries"
version = "0.5.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-jinja2 = "0.0.5"
tree-sitter-rust = "0.20.4"
dashmap = "5.1.0"
tower-lsp = { version = "0.20.0", features = ["proposed"] }

